### ISSUE TITLE
Incompatible with 1.19.2

### ISSUE THREAD

**Issue by Sunconure11** [Klyser8/Eggstra#4]
https://pastebin.com/7vHx32wn

**Comment by AivanF** [comment]
The above link doesn't work, let me post log here. I don't believe anyone will solve it, but why not 😁

```java
---- Minecraft Crash Report ----
// Everything's going to plan. No, really, that was supposed to happen.

Time: 2023-10-12 17:16:02
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'eggstra'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:459)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoSuchMethodError: 'void net.minecraft.class_1813.<init>(int, net.minecraft.class_3414, net.minecraft.class_1792$class_1793)'
	at com.github.klyser8.eggstra.item.EggstraRecordItem.<init>(EggstraRecordItem.java:8)
	at com.github.klyser8.eggstra.registry.EggstraItems.lambda$static$3(EggstraItems.java:34)
	at com.github.klyser8.eggstra.platform.fabric.CommonPlatformHelperImpl.registerItem(CommonPlatformHelperImpl.java:24)
	at com.github.klyser8.eggstra.platform.CommonPlatformHelper.registerItem(CommonPlatformHelper.java)
	at com.github.klyser8.eggstra.registry.EggstraItems.<clinit>(EggstraItems.java:32)
	at com.github.klyser8.eggstra.Eggstra.init(Eggstra.java:10)
	at com.github.klyser8.eggstra.fabric.EggstraFabric.onInitialize(EggstraFabric.java:13)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 8 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:459)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Mac OS X (x86_64) version 11.2.3
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 640985872 bytes (611 MiB) / 1342177280 bytes (1280 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 13
	Microarchitecture: Coffee Lake
	Frequency (GHz): 2.40
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Memory slot #0 capacity (MB): 0.00
	Memory slot #0 clockSpeed (GHz): 0.00
	Memory slot #0 type: unknown
	Virtual memory max (MB): 36864.00
	Virtual memory used (MB): 22348.31
	Swap memory total (MB): 4096.00
	Swap memory used (MB): 3021.25
	JVM Flags: 7 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -Xmx4096m
	Fabric Mods: 
		animal_feeding_trough: Animal Feeding Trough 1.0.3+1.19.2
		architectury: Architectury 6.3.49
		balm-fabric: Balm 4.5.2+0
		bettersleeping: BetterSleeping 0.6.1+1.19
			bettersleeping-core: BetterSleeping Core 0.6.1
			org_apache_commons_commons-text: commons-text 1.9
		bowinfinityfix: Bow Infinity Fix 2.5.0
		cloth-config: Cloth Config v9 9.0.92
			cloth-basic-math: cloth-basic-math 0.6.1
		colytra: Colytra 6.0.0+1.19.2
			spectrelib: SpectreLib 0.8.1+1.19
		couplings: Couplings 1.9.1+1.19
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		diamond: Easy Diamond 1.19.2-1.6.3-[FABRIC]
		durabilityviewer: Giselbaers Durability Viewer 1.19.1-fabric0.58.5-1.10.3
			crowdin-translate: CrowdinTranslate 1.4+1.19
			gbfabrictools: GBfabrictools 1.3.4+1.19
		easierenchanting: Easier Enchanting 1.4.1
		eggstra: Eggstra 1.19-1.2.0a
		enchantinginfuser: Enchanting Infuser 4.2.2
		exlinefurniture: Exline's Furniture 2.3.2
		fabric-api: Fabric API 0.64.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.12+93d8cb8290
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.10+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.18+c6af733c90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.21+c6af733c90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.2+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.12+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.1.8+93d8cb8290
			fabric-commands-v0: Fabric Commands (v0) 0.2.29+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.35+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.4.0+6064db2a90
			fabric-convention-tags-v1: Fabric Convention Tags 1.1.2+93d8cb8290
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.6+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.2.2+b598f4ac90
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.32+0dd10df690
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.19+9ff28f4090
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.29+c6af733c90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.29+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.22+c6af733c90
			fabric-item-api-v1: Fabric Item API (v1) 1.5.8+93d8cb8290
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.32+70efcffe90
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.22+aaaf9d3390
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.20+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.0+33ffe9ec90
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.6+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.9+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.4+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.17+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.18+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.5+c6af733c90
			fabric-networking-v0: Fabric Networking (v0) 0.3.22+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.14+93d8cb8290
			fabric-particles-v1: Fabric Particles (v1) 1.0.11+79adfe0a90
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.26+c6af733c90
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.12+c0ae659d90
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.14+aeb40ebe90
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.21+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.15+aeb40ebe90
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.8+c6af733c90
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.23+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.11.0+73145abb90
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.0+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.7.2+70efcffe90
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.27+93d8cb8290
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.1+1cc24b1b90
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.0+c4f28df590
			fabric-textures-v0: Fabric Textures (v0) 1.0.21+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.1+93d8cb8290
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.1+42d99c3290
		fabricloader: Fabric Loader 0.14.19
		fallingtree: FallingTree 3.10.0
		fastload: Fast Load 1.2.1
		flesh2leather: Flesh2Leather 1.0.3+1.19
		forgeconfigapiport: Forge Config API Port 4.2.6
		grindenchantments: Grind Enchantments 2.0.0+1.19.2
		interactic: Interactic 0.1.11+1.19
		java: OpenJDK 64-Bit Server VM 17
		mcf-reap: MaxVar reap for fabric 1.7.1
		minecraft: Minecraft 1.19.2
		modmenu: Mod Menu 4.0.6
		mousewheelie: Mouse Wheelie 1.10.2+mc1.19-pre1
			amecsapi: Amecs API 1.3.6+mc22w17a
			coat: Coat 1.0.0-beta.18+mc22w17a
			tweed4_annotated: tweed4_annotated 1.3.1+mc22w17a
			tweed4_base: tweed4_base 1.6.0+mc22w17a
			tweed4_data: tweed4_data 1.2.1+mc22w17a
			tweed4_data_hjson: tweed4_data_hjson 1.1.1+mc22w17a
			tweed4_tailor_coat: tweed4_tailor_coat 1.1.3+mc22w17a
			tweed4_tailor_screen: tweed4_tailor_screen 1.1.1+mc22w17a
		netherite: Easy Netherite 1.19.2-1.1.3-[FABRIC]
		puzzleslib: Puzzles Lib 4.3.12
			cardinal-components-base: Cardinal Components API (base) 5.0.2
			cardinal-components-block: Cardinal Components API (blocks) 5.0.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.2
			cardinal-components-entity: Cardinal Components API (entities) 5.0.2
			cardinal-components-world: Cardinal Components API (worlds) 5.0.2
		ring_of_teleport: Ring Of Teleport 1.2.14
		simplehats: SimpleHats 1.19.2-0.1.6
		sodium: Sodium 0.4.4+build.18
			org_joml_joml: joml 1.10.4
		stacker: Stacker 3.0.2-1.19.x
			stacc: Stacc 1.3.4
		taxfreelevels: Tax Free Levels 1.3.3
		trinkets: Trinkets 3.4.2
		waystones: Waystones 11.1.0
		xaerominimap: Xaero's Minimap 22.16.0
		xaeroworldmap: Xaero's World Map 1.28.1
	Launched Version: fabric-loader-0.14.19-1.19.2
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>
```

**Comment by Sunconure11** [comment]
I can probably fix this at this point, along with Earthbounds.
